### ISSUE TITLE
Holding M1 vs. repeatedly clicking M1 for first primary

### ISSUE THREAD

**Issue by Arrrvid** [Moffein/BanditReloaded#1]
Currently repeatedly clicking M1 when using the first primary results in a much faster fire rate than simply holding M1. Is it possible to make the fire rates the same to prevent having to spam M1? Currently they are the same for the second primary

**Comment by Moffein** [comment]
This is an intended feature, a holdover from RoR1 where Bandit who could mash the fire button to shoot faster. Though the mod was balanced around the slower autofire fire rate, with the faster mashing fire rate being left as a goodie for those who want to use it.  There's a config option to disable/change this if you want.
